=== liferay/liferay-central-test-1/definitions/liferay-plugin-package_4_3_0.dtd
<!--
This is the DTD for the Liferay Plugins XML file that lists the plugins
available in a plugin repository

<!DOCTYPE plugin-package PUBLIC
	"-//Liferay//DTD Plugin Package 4.3.0//EN"
	"http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">
-->

<!--
A boolean type is the string representation of a boolean (true or false)
variable.
-->
<!ENTITY % boolean "(true|false|yes|no)">

<!--
The plugin element contains the declarative data of a plugin.
-->
<!ELEMENT plugin-package (name, module-id, installation-file-name?, types, tags?,
short-description, long-description?, page-url, screenshots?, author, licenses,
liferay-versions)>

<!--
The name element contains the name of the plugin package that will be shown to
the users.
-->
<!ELEMENT name (#PCDATA)>

<!--
The module-id element contains the full identifier of the plugin using the
Maven based syntax: groupId/artifactId/version/file-type.

Example: liferay-samples/sample-struts-portlet/4.2.1/war
-->
<!ELEMENT module-id (#PCDATA)>

<!--
The recommended-war-name element contains the recommended WAR name that will be
used to deploy this plugin.
-->
<!ELEMENT installation-file-name (#PCDATA)>

<!--
The types element contains a list of plugin types included in the package
-->
<!ELEMENT types (type)+>

<!--
The type element contains the type of the plugin. Valid values are: portlets,
layout-templates, and themes.
-->
<!ELEMENT type (#PCDATA)>

<!--
The tags element contains a list of tags to categorize this plugin.
-->
<!ELEMENT tags (tag)*>

<!--
The tag element contains a tag that categorizes to this plugin.
-->
<!ELEMENT tag (#PCDATA)>

<!--
The short-description element contains a short description of this plugin.
-->
<!ELEMENT short-description (#PCDATA)>

<!--
The long-description element contains a detailed description of this plugin. It
is recommended that installation or update instructions are provided if the
portal administrator has to perform extra steps to be able to use the plugin
after it is deployed.

Note: the text of this element might contain simple HTML formatting if encoded
within a CDATA section.
-->
<!ELEMENT long-description (#PCDATA)>

<!--
The page-url element contains the URL of the home page of the plugin.
-->
<!ELEMENT page-url (#PCDATA)>

<!--
The screenshots element contains a list of screenshots for the plugin.
-->
<!ELEMENT screenshots (screenshot)+>

<!--
The screenshot element contains two URLs for the thumbnail and large images
versions of the screenshot
-->
<!ELEMENT screenshot (thumbnail-url,large-image-url)>

<!--
The thumbnail-url element contains the URL of a screenshot of the plugin.
It is recommended that the width of the images is 120 pixels and that the height
is in the same size range.
-->
<!ELEMENT thumbnail-url (#PCDATA)>

<!--
The large-image-url element contains the URL of a screenshot of the plugin.
It is recommended that the width of the images is 120 pixels and that the height
is in the same size range.
-->
<!ELEMENT large-image-url (#PCDATA)>

<!--
The author element contains the name of the author of the plugin.
-->
<!ELEMENT author (#PCDATA)>

<!--
The licenses element contains a list of licence under which this plugin is
provided.
-->
<!ELEMENT licenses (license)+>

<!--
The license element contains the name of a licence under which this plugin is
provided.
-->
<!ELEMENT license (#PCDATA)>

<!--
The osi-approved attribute specifies if the license is open source, approved by
the Open Source Initiative (OSI). In that case it's value is true.
-->
<!ATTLIST license
	osi-approved %boolean; #REQUIRED
>

<!--
The url attribute specifies a URL of a page that describes the license.
-->
<!ATTLIST license
	url CDATA #IMPLIED
>

<!--
The liferay-versions element contains a list of Liferay Portal versions that
are supported by this plugin.
-->
<!ELEMENT liferay-versions (liferay-version)+>

<!--
The liferay-version element contains a version of Liferay Portal that is
supported by this plugin.
-->
<!ELEMENT liferay-version (#PCDATA)>

=== liferay/liferay-central-test-1/portlets/alfresco.war.ext/WEB-INF/liferay-plugin-package.xml
<?xml version="1.0"?>
<!DOCTYPE plugin-package PUBLIC "-//Liferay//DTD Plugin Package 4.3.0//EN" "http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">

<plugin-package>
	<name>Alfresco Client</name>
	<module-id>alfresco/client/4.3.0/war</module-id>
	<types>
		<type>portlet</type>
	</types>
	<short-description>
		Access the Alfresco UI as a portlet
	</short-description>
	<page-url>http://www.liferay.com/web/guest/downloads<page-url>
	<liferay-versions>
		<liferay-version>4.2.*</liferay-version>
	</liferay-versions>
</plugin-package>

=== liferay/liferay-central-test-1/portlets/sample-portal-service-portlet.war/WEB-INF/liferay-plugin-package.xml
<?xml version="1.0"?>
<!DOCTYPE plugin-package PUBLIC "-//Liferay//DTD Plugin Package 4.3.0//EN" "http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">

<plugin-package>
	<name>Sample Portal Service Portlet</name>
	<module-id>liferay-samples/sample-portal-service-portlet/4.3.0/war</module-id>
	<types>
		<type>portlet</type>
	</types>
	<short-description>
		This portlet shows how to use Liferay's services throught regular Java calls
	</short-description>
	<page-url>http://www.liferay.com/web/guest/downloads<page-url>
	<liferay-versions>
		<liferay-version>4.2.*</liferay-version>
	</liferay-versions>
</plugin-package>

=== liferay/liferay-central-test-1/themes/sample-unstyled-theme.war/WEB-INF/liferay-plugin-package.xml
<?xml version="1.0"?>
<!DOCTYPE plugin-package PUBLIC "-//Liferay//DTD Plugin Package 4.3.0//EN" "http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">

<plugin-package>
	<name>Sample Unstyled Theme</name>
	<module-id>liferay-samples/sample-unstyled-theme/4.3.0/war</module-id>
	<types>
		<type>theme</type>
	</types>
	<tags>
		<tag>sample</tag>
	</tags>
	<short-description>
		This is a sample unstyled theme with configuration set in
		liferay-look-and-feel.xml.
	</short-description>
	<change-log>
		Adapted to the latest version of Liferay.
	</change-log>
	<page-url>http://www.liferay.com/web/guest/downloads</page-url>
	<author>Liferay, Inc.</author>
	<licenses>
		<license osi-approved="true">MIT</license>
	</licenses>
	<liferay-versions>
		<liferay-version>4.3.*</liferay-version>
	</liferay-versions>
</plugin-package>

=== liferay/liferay-central-test-1/themes/sample-base-wap-theme.war/WEB-INF/liferay-plugin-package.xml
<?xml version="1.0"?>
<!DOCTYPE plugin-package PUBLIC "-//Liferay//DTD Plugin Package 4.3.0//EN" "http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">

<plugin-package>
	<name>Sample Base WAP Theme</name>
	<module-id>liferay-samples/sample-base-wap-theme/4.2.1/war</module-id>
	<types>
		<type>theme</type>
	</types>
	<tags>
		<tag>sample</tag>
	</tags>
	<short-description>
		This is a base theme for WAP clients.
	</short-description>
	<change-log>
		Adapted to the latest version of Liferay.
	</change-log>
	<page-url>http://www.liferay.com/web/guest/downloads/samples</page-url>
	<author>Liferay, Inc.</author>
	<licenses>
		<license osi-approved="true">MIT</license>
	</licenses>
	<liferay-versions>
		<liferay-version>4.2.*</liferay-version>
	</liferay-versions>
</plugin-package>

=== liferay/liferay-central-test-1/portlets/sample-spring-portlet.war.ext/WEB-INF/liferay-plugin-package.xml
<?xml version="1.0"?>
<!DOCTYPE plugin-package PUBLIC "-//Liferay//DTD Plugin Package 4.3.0//EN" "http://www.liferay.com/dtd/liferay-plugin-package_4_3_0.dtd">

<plugin-package>
	<name>Sample Spring Portlet</name>
	<module-id>liferay-samples/sample-spring-portlet/4.3.0/war</module-id>
	<types>
		<type>portlet</type>
	</types>
	<tags>
		<tag>sample</tag>
	</tags>
	<short-description>
		This portlet shows how to use Spring within Liferay.
	</short-description>
	<change-log>
		Adapted to the latest version of Liferay
	</change-log>
	<page-url>http://www.liferay.com/web/guest/downloads</page-url>
	<author>Interface21</author>
	<licenses>
		<license osi-approved="true">Apache</license>
	</licenses>
	<liferay-versions>
		<liferay-version>4.2.*</liferay-version>
	</liferay-versions>
</plugin-package>
