=== liferay/liferay-central-test-1/definitions/liferay-friendly-url-routes_6_0_0.dtd
<!--
This is the DTD for the Friendly URL Routes parameters for Liferay Portal.

<!DOCTYPE routes PUBLIC
	"-//Liferay//DTD Friendly URL Routes 6.0.0//EN"
	"http://www.liferay.com/dtd/liferay-friendly-url-routes_6_0_0.dtd">
-->

<!--
The routes element is the root of the deployment descriptor for a set of Liferay
friendly URL mapper routes.
-->
<!ELEMENT routes (route*)>

<!--
The route element contains information on a single route.
-->
<!ELEMENT route (pattern, default-parameter*)>

<!--
The pattern element specifies the pattern of the mapped friendly URL.
-->
<!ELEMENT pattern (#PCDATA)>

<!--
The default-parameter element specifies a default parameter that is not preset
in the route pattern.
-->
<!ELEMENT default-parameter (#PCDATA)>

<!--
The name attribute specifies the name of the default URL parameter.
-->
<!ATTLIST default-parameter
	name CDATA #REQUIRED
>

=== liferay/liferay-central-test-1/portal-impl/src/com/liferay/portlet/wiki/wiki-friendly-url-routes.xml
<?xml version="1.0"?>
<!DOCTYPE routes PUBLIC "-//Liferay//DTD Friendly URL Routes 6.0.0//EN" "http://www.liferay.com/dtd/liferay-friendly-url-routes_6_0_0.dtd">

<routes>
	<route>
		<pattern>/tag/{tag}</pattern>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_tagged_pages</default-parameter>
		<ignored-parameter name="nodeId" />
		<ignored-parameter name="nodeName" />
	</route>
	<route>
		<pattern>/{nodeId:\d+}/all_pages</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_all_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/draft_pages</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_draft_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/orphan_pages</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_orphan_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/recent_changes</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_recent_changes</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/all_pages</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_all_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/draft_pages</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_draft_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/orphan_pages</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_orphan_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/recent_changes</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view_recent_changes</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/{title:[^/]+}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/{title:[^/]+}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="p_p_state">normal</default-parameter>
		<default-parameter name="struts_action">/wiki/view</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/tag/{tag}/{p_p_state}</pattern>
		<default-parameter name="struts_action">/wiki/view_tagged_pages</default-parameter>
		<ignored-parameter name="nodeId" />
		<ignored-parameter name="nodeName" />
	</route>
	<route>
		<pattern>/{nodeId:\d+}/all_pages/{p_p_state}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_all_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/draft_pages/{p_p_state}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_draft_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/orphan_pages/{p_p_state}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_orphan_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/recent_changes/{p_p_state}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_recent_changes</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/all_pages/{p_p_state}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_all_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/draft_pages/{p_p_state}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_draft_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/orphan_pages/{p_p_state}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_orphan_pages</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/recent_changes/{p_p_state}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="struts_action">/wiki/view_recent_changes</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeId:\d+}/{title:[^/]+}/{p_p_state}</pattern>
		<default-parameter name="nodeName"></default-parameter>
		<default-parameter name="struts_action">/wiki/view</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
	<route>
		<pattern>/{nodeName}/{title:[^/]+}/{p_p_state}</pattern>
		<default-parameter name="nodeId"></default-parameter>
		<default-parameter name="struts_action">/wiki/view</default-parameter>
		<default-parameter name="tag"></default-parameter>
	</route>
</routes>
